### Signup

POST {{base_url}}/users/signup/ HTTP/1.1
Content-Type: application/json

{
  "email": "test@gmail.com",
  "full_name": "Test",
  "password": "noufal123",
  "platform": "mobile",
  "referral_code_input": "NOUFAL",
  "username": "test"
}

> {%
  var cookieHeader = response.headers.valueOf("Set-Cookie");

  if (cookieHeader) {
      var match = cookieHeader.match(/access_token=([^;]+)/);

      if (match) {
          client.global.set("token", match[1]);
      }
  }
  else{
      client.global.set("token", response.body.access)
    }
%}


### Login

POST {{base_url}}/users/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "noufal@email.com",
  "password": "noufal",
  "platform": "mobile"
}

> {%
  var cookieHeader = response.headers.valueOf("Set-Cookie");

  if (cookieHeader) {
      var match = cookieHeader.match(/access_token=([^;]+)/);

      if (match) {
          client.global.set("token", match[1]);
      }
  }
  else{
      client.global.set("token", response.body.access)
      client.global.set("refresh", response.body.refresh)
    }
%}


### Logout

POST {{base_url}}/users/logout/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "{{refresh}}"
}


### Change Password

POST {{base_url}}/users/change-password/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current_password": "passowrd123",
  "new_password": "password1x3"
}


### Reset Password

POST {{base_url}}/users/reset-password/ HTTP/1.1
Content-Type: application/json

{
  "email": "demo8@email.com",
  "new_password": "noufal2"
}


### Delete Account

DELETE {{base_url}}/users/profile/delete/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "refresh": "{{refresh}}"
}
