### Signup Request OTP

POST {{base_url}}/users/signup-request-otp/ HTTP/1.1
Content-Type: application/json

{
  "email": "test@gmail.com"
}


### Signup Verify OTP

POST {{base_url}}/users/signup-verify-otp/ HTTP/1.1
Content-Type: application/json

{
  "email": "test@gmail.com",
  "otp": "443992"
}


### Password Reset Request OTP

POST {{base_url}}/users/password-reset-request-otp/ HTTP/1.1
Content-Type: application/json

{
  "email": "noufal@email.com"
}


### Password Reset Verify OTP

POST {{base_url}}/users/password-reset-verify-otp/ HTTP/1.1
Content-Type: application/json

{
  "email": "demo1@email.com",
  "otp": "002089"
}
