### Signup Request OTP

POST {{base_url}}/users/signup-request-otp/ HTTP/1.1
Content-Type: application/json

{
  "email": "demo9@email.com"
}


### Signup Verify OTP

POST {{base_url}}/users/signup-verify-otp/ HTTP/1.1
Content-Type: application/json

{
  "email": "demo8@email.com",
  "otp": "460117"
}


### Password Reset Request OTP

POST {{base_url}}/users/password-reset-request-otp/ HTTP/1.1
Content-Type: application/json

{
  "email": "demo11@email.com"
}


### Password Reset Verify OTP

POST {{base_url}}/users/password-reset-verify-otp/ HTTP/1.1
Content-Type: application/json

{
  "email": "demo8@email.com",
  "otp": "013985"
}
