### GET Profile

GET {{base_url}}/users/profile/me/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET Business Profile

GET {{base_url}}/users/business-profile/me/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
