# Generated by Django 6.0.2 on 2026-02-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
