# Generated by Django 6.0.2 on 2026-02-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
