# Generated by Django 6.0.1 on 2026-05-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_type',
            field=models.CharField(choices=[('QTY', 'Quantity'), ('HRS', 'Hours'), ('DAYS', 'Days')], default='QTY', max_length=4),
        ),
    ]
