### GET Clients

GET {{base_url}}/clients/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Client Lookup

POST {{base_url}}/client-lookup/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone_number": "+919746469319"
}

> {%

  client.global.set("client_id", response.body.client_id )

%}
