### GET Reviews

GET {{base_url}}/client/{{client_id}}/reviews/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET Reviews Summary

GET {{base_url}}/client/{{client_id}}/reviews/summary/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### POST Review

POST {{base_url}}/client/{{client_id}}/reviews/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ratings": 1,
  "tags": [
    14,
    16
  ]
}
