### GET Books

GET {{base_url}}/books/ HTTP/1.1
Content-Type: application/json


### POST Books

POST {{base_url}}/books/ HTTP/1.1
Content-Type: application/json

{
  "name": "Patti jeevitham",
  "price": 2000
}
