# Generated by Django 6.0.1 on 2026-04-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
