# Generated by Django 6.0.1 on 2026-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
